# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/simpleProjects/Zybo_contraints.xdc

# Block Designs: bd/PushButton/PushButton.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PushButton || ORIG_REF_NAME==PushButton} -quiet] -quiet

# IP: bd/PushButton/ip/PushButton_processing_system7_0_0/PushButton_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PushButton_processing_system7_0_0 || ORIG_REF_NAME==PushButton_processing_system7_0_0} -quiet] -quiet

# IP: bd/PushButton/ip/PushButton_axi_gpio_0_0/PushButton_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PushButton_axi_gpio_0_0 || ORIG_REF_NAME==PushButton_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PushButton/ip/PushButton_ps7_0_axi_periph_0/PushButton_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PushButton_ps7_0_axi_periph_0 || ORIG_REF_NAME==PushButton_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/PushButton/ip/PushButton_rst_ps7_0_50M_0/PushButton_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PushButton_rst_ps7_0_50M_0 || ORIG_REF_NAME==PushButton_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/PushButton/ip/PushButton_auto_pc_0/PushButton_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PushButton_auto_pc_0 || ORIG_REF_NAME==PushButton_auto_pc_0} -quiet] -quiet

# XDC: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/simpleProjects/LedPushButton/LedPushButton.gen/sources_1/bd/PushButton/PushButton_ooc.xdc
