# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_z7_20_contraints.xdc

# Block Designs: bd/simple1/simple1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple1 || ORIG_REF_NAME==simple1} -quiet] -quiet

# IP: bd/simple1/ip/simple1_processing_system7_0_0/simple1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple1_processing_system7_0_0 || ORIG_REF_NAME==simple1_processing_system7_0_0} -quiet] -quiet

# IP: bd/simple1/ip/simple1_axi_gpio_0_0/simple1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple1_axi_gpio_0_0 || ORIG_REF_NAME==simple1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/simple1/ip/simple1_ps7_0_axi_periph_0/simple1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple1_ps7_0_axi_periph_0 || ORIG_REF_NAME==simple1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/simple1/ip/simple1_rst_ps7_0_50M_0/simple1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple1_rst_ps7_0_50M_0 || ORIG_REF_NAME==simple1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/simple1/ip/simple1_auto_pc_0/simple1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simple1_auto_pc_0 || ORIG_REF_NAME==simple1_auto_pc_0} -quiet] -quiet

# XDC: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/sinpleProjects/ledOn/ledOn.gen/sources_1/bd/simple1/simple1_ooc.xdc
