# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/zybo_z7_20_base_2021_1/hardware/zybo_z7_base_2021_1-vivado/zybo_z7_base_2021_1-vivado.srcs/sources_1/bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_auto_pc_0/zybo_z7_20_base_2021_1_auto_pc_0.xci
# IP: The module: 'zybo_z7_20_base_2021_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/zybo_z7_20_base_2021_1/hardware/zybo_z7_base_2021_1-vivado/zybo_z7_base_2021_1-vivado.gen/sources_1/bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_auto_pc_0/zybo_z7_20_base_2021_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_z7_20_base_2021_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/zybo_z7_20_base_2021_1/hardware/zybo_z7_base_2021_1-vivado/zybo_z7_base_2021_1-vivado.srcs/sources_1/bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_auto_pc_0/zybo_z7_20_base_2021_1_auto_pc_0.xci
# IP: The module: 'zybo_z7_20_base_2021_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/zybo_z7_20_base_2021_1/hardware/zybo_z7_base_2021_1-vivado/zybo_z7_base_2021_1-vivado.gen/sources_1/bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_auto_pc_0/zybo_z7_20_base_2021_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_z7_20_base_2021_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
