# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zybo_z7_20_base_2021_1/zybo_z7_20_base_2021_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1 || ORIG_REF_NAME==zybo_z7_20_base_2021_1} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_processing_system7_0_0/zybo_z7_20_base_2021_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_processing_system7_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_clk_wiz_0_0/zybo_z7_20_base_2021_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_clk_wiz_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_proc_sys_reset_0_0/zybo_z7_20_base_2021_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_proc_sys_reset_0_1/zybo_z7_20_base_2021_1_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_1 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_proc_sys_reset_0_2/zybo_z7_20_base_2021_1_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_2 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_proc_sys_reset_0_3/zybo_z7_20_base_2021_1_proc_sys_reset_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_3 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_3} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_proc_sys_reset_0_4/zybo_z7_20_base_2021_1_proc_sys_reset_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_4 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_proc_sys_reset_0_4} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_axi_intc_0_0/zybo_z7_20_base_2021_1_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_axi_intc_0_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_axi_intc_0_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_auto_pc_0/zybo_z7_20_base_2021_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_auto_pc_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_auto_pc_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_ps7_0_axi_periph_0/zybo_z7_20_base_2021_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zybo_z7_20_base_2021_1/ip/zybo_z7_20_base_2021_1_rst_ps7_0_50M_0/zybo_z7_20_base_2021_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zybo_z7_20_base_2021_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==zybo_z7_20_base_2021_1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/ayuba/Zybo_Image_Processing/Zybo_Image_Processing/workspace/zybo_z7_20_base_2021_1/hardware/zybo_z7_base_2021_1-vivado/zybo_z7_base_2021_1-vivado.gen/sources_1/bd/zybo_z7_20_base_2021_1/zybo_z7_20_base_2021_1_ooc.xdc
